In [39]:
import numpy as np

In [89]:
#Obtener datos del usuario:
print('Ingrese los datos solicitados')
print('1.Ingrese su edad: ')
edad=int(input())
print('2.Ingrese su altura en cm: ')
altura=int(input())
print('3.Ingrese su peso en kg: ')
peso=int(input())
print('4.Ingrese su género [H/M]: ')
gen=input()
print('4.Presión sistólica: ')
ps=int(input())
print('5.Presión diástolica: ')
pd=int(input())
print('6.Nivel de colesterol: ')
col=int(input())
print('7.Nivel de glucosa: ')
gluc=int(input())
print('9.¿Fuma? [S/N]: ')
fum=input()
print('10.¿Consume alcohol? [S/N]: ')
alco=input()
print('11.¿Se ejercita cotidianamente? [S/N]: ')
ejer=input()

Ingrese los datos solicitados
1.Ingrese su edad: 
34
2.Ingrese su altura en cm: 
160
3.Ingrese su peso en kg: 
90
4.Ingrese su género [H/M]: 
h
4.Presión sistólica: 
135
5.Presión diástolica: 
80
6.Nivel de colesterol: 
200
7.Nivel de glucosa: 
110
9.¿Fuma? [S/N]: 
s
10.¿Consume alcohol? [S/N]: 
n
11.¿Se ejercita cotidianamente? [S/N]: 
n


In [43]:
def prueba_col(colest):
    if colest<200:
        return 1
    elif colest>=200 and colest<240:
        return 2
    else:
        return 3

In [70]:
col_fin=prueba_col(col)
col_fin

1

In [49]:
def prueba_glucosa(gluc):
    if gluc<110:
        return 1
    elif gluc>=110 and gluc<130:
        return 2
    else:
        return 3

In [71]:
glu_fin=prueba_glucosa(gluc)
glu_fin

2

In [56]:
def tabaco(f):
    if f=='s' or f=='S':
        return 1
    else:
        return 0

In [72]:
tab_fin=tabaco(fum)
tab_fin

1

In [62]:
def ejerc(f):
    if f=='s' or f=='S':
        return 1
    else:
        return 0

In [82]:
ejer_fin=ejerc(ejer)

In [78]:
def alcoh(f):
    if f=='s' or f=='S':
        return 1
    else:
        return 0

In [80]:
alco_fin=alcoh(alco)

In [90]:
def genero(f):
    if f=='M' or f=='m':
        return 2
    else:
        return 1

In [92]:
gen_final=genero(gen)

In [66]:
def IMC(alt,pes):
    return round((pes*10000)/(alt**2),2)

In [73]:
IMC(altura,peso)

27.55

In [83]:
imc_fin=IMC(altura,peso)

In [108]:
prueba_cardio=[[edad,gen_final,altura,peso,ps,pd,col_fin,glu_fin,
                tab_fin,alco_fin,ejer_fin,imc_fin]]

In [109]:
prueba_cardio

[[34, 1, 160, 90, 135, 80, 1, 2, 1, 0, 0, 27.55]]

In [95]:
import pickle

In [96]:
modelo = pickle.load(open('Datos/modelo_svc.sav', 'rb'))

In [110]:
modelo.predict(prueba_cardio)

array([0])

In [122]:
prueba_cardio2=[[75,1,168,90,110,80,2,3,1,0,1,31.97]]

In [123]:
modelo.predict(prueba_cardio2)

array([1])

In [124]:
prueba_cardio3=[[25,2,160,68,120,80,1,1,1,0,0,26.6]]

In [125]:
modelo.predict(prueba_cardio3)

array([0])

In [128]:
prueba_cardio4=[[62,2,155,60,120,80,3,3,1,1,0,25]]

In [139]:
modelo.predict(prueba_cardio4+prueba_cardio3)

array([1, 0])

In [130]:
resultado=modelo.predict(prueba_cardio4)

In [133]:
resultado[0]

1

In [140]:
def get_data():
    print('1.Ingrese su edad: ')
    edad=int(input())
    print('2.Ingrese su altura en cm: ')
    altura=int(input())
    print('3.Ingrese su peso en kg: ')
    peso=int(input())
    print('4.Ingrese su género [H/M]: ')
    gen=input()
    print('4.Presión sistólica: ')
    ps=int(input())
    print('5.Presión diástolica: ')
    pd=int(input())
    print('6.Nivel de colesterol: ')
    col=int(input())
    print('7.Nivel de glucosa: ')
    gluc=int(input())
    print('9.¿Fuma? [S/N]: ')
    fum=input()
    print('10.¿Consume alcohol? [S/N]: ')
    alco=input()
    print('11.¿Se ejercita cotidianamente? [S/N]: ')
    ejer=input()
    return [edad,altura,peso,gen,ps,pd,col,gluc,fum,alco,ejer]

In [141]:
datos=get_data()

1.Ingrese su edad: 
62
2.Ingrese su altura en cm: 
155
3.Ingrese su peso en kg: 
65
4.Ingrese su género [H/M]: 
m
4.Presión sistólica: 
120
5.Presión diástolica: 
90
6.Nivel de colesterol: 
135
7.Nivel de glucosa: 
150
9.¿Fuma? [S/N]: 
s
10.¿Consume alcohol? [S/N]: 
s
11.¿Se ejercita cotidianamente? [S/N]: 
n


In [142]:
datos

[62, 155, 65, 'm', 120, 90, 135, 150, 's', 's', 'n']

In [150]:
def prueba_datos(data):
    edad=data[0]
    altura=data[1]
    peso=data[2]
    ps=data[4]
    pd=data[5]
    col_fin=prueba_col(data[6])
    glu_fin=prueba_glucosa(data[7])
    tab_fin=tabaco(data[8])
    ejer_fin=ejerc(data[10])
    alco_fin=alcoh(data[9])
    gen_final=genero(data[3])
    imc_fin=IMC(altura,peso)
    return [[edad,gen_final,altura,peso,ps,pd,col_fin,glu_fin,
                tab_fin,alco_fin,ejer_fin,imc_fin]]

In [152]:
prueba_final=prueba_datos(datos)
prueba_final

[[62, 2, 155, 65, 120, 90, 1, 3, 1, 1, 0, 27.06]]

In [145]:
resul_fin=modelo.predict(prueba_final)
resul_fin

array([0])

In [153]:
def resultado(r):
    if r==0:
        print('Baja probabilidad de desarrollar una enfermedad cardiovascular')
    else:
        print('Alta probabilidad de desarrollar enfermedad cardiovascular')

In [154]:
resultado(resul_fin[0])

Baja probabilidad de desarrollar una enfermedad cardiovascular
